{% set name = "gwtc_analysis" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gwtc-analysis/gwtc_analysis-{{ version }}.tar.gz
  sha256: 66886234e5e5aafdbbee94f972de720eba84d6a517ce32804bdca7781825e0d4

build:
  skip: true  # [win]
  number: 0
  entry_points:
    - gwtc_analysis = gwtc_analysis.cli:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - astropy-base
    - gwosc
    - gwpy
    - h5py
    - healpy
    - ligo.skymap
    - pesummary
    - pycbc
    - pyyaml
    - numpy
    - pandas
    - matplotlib-base
    - minio
    - requests
    - scipy
    - tqdm

test:
  imports:
    - gwtc_analysis
  commands:
    - gwtc_analysis --help
    - gwtc_analysis parameters_estimation -h
  requires:
    - pip

about:
  home: https://pypi.org/project/gwtc-analysis/
  dev_url: https://github.com/danielsentenac/gwtc_analysis
  summary: GWTC analysis utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielsentenac
